# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Аноды',
                'verbose_name': 'Анод',
            },
        ),
        migrations.CreateModel(
            name='wavelength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('wavelength', models.DecimalField(blank=True, decimal_places=6, help_text='in Angstrom unit', max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'длины',
                'verbose_name': 'длина',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='anod',
            name='wavelength',
            field=models.ManyToManyField(to='diffraction.wavelength'),
        ),
    ]
