# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diffraction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_of_calcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JSON', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=100)),
                ('data_start', models.DateTimeField(auto_now_add=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Расчет',
                'verbose_name_plural': 'Расчеты',
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
        ),
        migrations.AddField(
            model_name='list_of_calcs',
            name='PC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffraction.PC'),
        ),
    ]
