# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diffraction', '0003_auto_20170305_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='date_here',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
