# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crystals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'кристалл',
                'verbose_name_plural': 'кристаллы',
            },
        ),
    ]
