# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polarizability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystals',
            name='a',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in Angstrom unit', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='crystals',
            name='alfa',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in degrees unit', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='crystals',
            name='b',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in Angstrom unit', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='crystals',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in degrees unit', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='crystals',
            name='c',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in Angstrom unit', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='crystals',
            name='crystal_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crystals',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in gr/cm^3, example, pSi = 2.33', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='crystals',
            name='gamma',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in degrees unit', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='crystals',
            name='short_name',
            field=models.CharField(blank=True, help_text='chemical formula', max_length=30, null=True),
        ),
    ]
