# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polarizability', '0002_auto_20161221_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('wavelength', models.DecimalField(blank=True, decimal_places=4, help_text='in Angstrom unit', max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'лабораторный источник',
                'verbose_name_plural': 'лабораторные источники',
            },
        ),
        migrations.AlterField(
            model_name='crystals',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in gr/cm^3, example, pSi = 2.33 gr/cm^3', max_digits=5, null=True),
        ),
    ]
