# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polarizability', '0003_auto_20161221_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_source',
            name='wavelength',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='in Angstrom unit', max_digits=6, null=True),
        ),
    ]
