# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polarizability', '0004_auto_20161221_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystals',
            name='a',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in Angstrom unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='crystals',
            name='alfa',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in degrees unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='crystals',
            name='b',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in Angstrom unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='crystals',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in degrees unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='crystals',
            name='c',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in Angstrom unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='crystals',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in gr/cm^3, example, pSi = 2.33 gr/cm^3', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='crystals',
            name='gamma',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in degrees unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lab_source',
            name='wavelength',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='in Angstrom unit', max_digits=10, null=True),
        ),
    ]
