# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polarizability', '0005_auto_20161221_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lab_source',
        ),
    ]
