# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polarizability', '0007_auto_20170121_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crystals',
            options={'ordering': ('name',), 'verbose_name': 'кристалл', 'verbose_name_plural': 'кристаллы'},
        ),
    ]
