# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='feedback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
