# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updates',
            options={'ordering': ['-date'], 'verbose_name': 'одновление', 'verbose_name_plural': 'обновления'},
        ),
    ]
